### ISSUE TITLE
Regarding recyclerview adapter.

### ISSUE THREAD

**Issue by PRIMA-RT** [MayconCardoso/Mvvm-Architecture-Toolkit#2]
Why you have used `ListAdapter` instead of `recyclerview.adapter` in `SimpleBindingAdapter`??
Is there any specific reason for it? as I know it is better to use recyclerview.adapter.
Could pls tell more abt it.
@MayconCardoso

**Comment by MayconCardoso** [comment]
Hey @Stkrr002, in fact [ListAdapter](https://developer.android.com/reference/androidx/recyclerview/widget/ListAdapter)  is a `recyclerview.adapter`. I decided to use a ListAdapter there to make it simpler given it encapsulates a few methods you would need to override otherwise using the base recycler view adapter. 

It also give you auto of the box the [AsyncListDiffer](https://developer.android.com/reference/androidx/recyclerview/widget/AsyncListDiffer) strategy to make changes on items more effectively.

**Comment by PRIMA-RT** [comment]
Thanks @MayconCardoso , gotcha

**Comment by MayconCardoso** [comment]
Closing the issue after explanation
